CREATE DATABASE IF NOT EXISTS `tasktracker` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE `tasktracker`;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `emaillog` (
  `EMAILLOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DATUM` date DEFAULT NULL,
  PRIMARY KEY (`EMAILLOG_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `klijent` (
  `KLIJENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAZIV` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ADRESA` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BROJ_TELEFONA` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EMAIL` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VIDLJIVO` bit(1) DEFAULT NULL,
  PRIMARY KEY (`KLIJENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `korisnik` (
  `KORISNIK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PREZIME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `JMBG` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BR_LK` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ADRESA` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TELEFON` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EMAIL` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `KORISNICKO_IME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LOZINKA` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DATUM_ZAPOSLENJA` datetime DEFAULT NULL,
  `VIDLJIVO` bit(1) DEFAULT NULL,
  `TIPKORISNIKA_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`KORISNIK_ID`),
  UNIQUE KEY `KORISNICKO_IME` (`KORISNICKO_IME`),
  KEY `FK_bolggaaus8of25ilqwyx6ctk5` (`TIPKORISNIKA_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=2 ;

INSERT INTO `korisnik` (`KORISNIK_ID`, `IME`, `PREZIME`, `JMBG`, `BR_LK`, `ADRESA`, `TELEFON`, `EMAIL`, `KORISNICKO_IME`, `LOZINKA`, `DATUM_ZAPOSLENJA`, `VIDLJIVO`, `TIPKORISNIKA_ID`) VALUES
(1, '', '', '', '', '', '', '', 'admin', '92668751', NULL, b'1', 1);

CREATE TABLE IF NOT EXISTS `obavljeniposao` (
  `OBAVLJENIPOSAO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RASPOREDJENIZADATAK_ID` bigint(20) NOT NULL,
  `VRSTAUSLUGE_ID` bigint(20) NOT NULL,
  `BROJSATI` int(11) DEFAULT NULL,
  `DATUMUNOSA` date DEFAULT NULL,
  `DATUMOBAVLJANJA` date DEFAULT NULL,
  `OPISA` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VIDLJIVO` bit(1) DEFAULT NULL,
  PRIMARY KEY (`OBAVLJENIPOSAO_ID`),
  KEY `FK_23n0532j0vfi8hichpybgugid` (`RASPOREDJENIZADATAK_ID`),
  KEY `FK_rqj2qh1veg6pvxla9fexnp2kr` (`VRSTAUSLUGE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `postavkamail` (
  `POSTAVKAMAIL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROKUNOS` int(11) DEFAULT NULL,
  `ROKPREUZIMANJE` int(11) DEFAULT NULL,
  `OPOMENA` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `OBAVIJEST` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`POSTAVKAMAIL_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=2 ;

INSERT INTO `postavkamail` (`POSTAVKAMAIL_ID`, `ROKUNOS`, `ROKPREUZIMANJE`, `OPOMENA`, `OBAVIJEST`) VALUES
(1, 1, 2, 'Molimo Vas da preuzmete zadatke\nkoje niste preuzeli.', 'Molimo vas da evidentirate zadatke\nkoje niste evidentirali.');

CREATE TABLE IF NOT EXISTS `radnizadatak` (
  `RADNIZADATAK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `KLIJENT_ID` bigint(20) NOT NULL,
  `KORISNIK_ID` bigint(20) NOT NULL,
  `BROJSERVISERA` int(11) DEFAULT NULL,
  `STATUSDODJELJENOSTI` int(11) DEFAULT NULL,
  `DATUMUNOSA` date DEFAULT NULL,
  `KRAJNJIDATUMIZVRSENJA` date DEFAULT NULL,
  `POTPUNODODJELJEN` bit(1) DEFAULT NULL,
  `STATUSIZVRSENOSTI` bit(1) DEFAULT NULL,
  `VIDLJIVO` bit(1) DEFAULT NULL,
  `OPIS` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VRSTAZADATKA` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`RADNIZADATAK_ID`),
  KEY `FK_ayvlsrkc6m5vv7udcxk5rhghi` (`KLIJENT_ID`),
  KEY `FK_mweelv44lv4n1yug7hevpxbi0` (`KORISNIK_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `rasporedjenizadatak` (
  `RASPOREDJENIZADATAK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RADNIZADATAK_ID` bigint(20) NOT NULL,
  `KORISNIK_ID` bigint(20) NOT NULL,
  `STATUSPRIHVACENOSTI` bit(1) DEFAULT NULL,
  `VIDLJIVO` bit(1) DEFAULT NULL,
  `DATUMPRIHVATANJA` date DEFAULT NULL,
  PRIMARY KEY (`RASPOREDJENIZADATAK_ID`),
  KEY `FK_4th26di53x8n0hito9634g2ic` (`RADNIZADATAK_ID`),
  KEY `FK_32527bsqg0565avppt85kb6pt` (`KORISNIK_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `tipkorisnika` (
  `TIPKORISNIKA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAZIV` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VIDLJIVO` bit(1) DEFAULT NULL,
  PRIMARY KEY (`TIPKORISNIKA_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=3 ;

INSERT INTO `tipkorisnika` (`TIPKORISNIKA_ID`, `NAZIV`, `VIDLJIVO`) VALUES
(1, 'Racunovodstvo', b'1'),
(2, 'Serviser', b'1');

CREATE TABLE IF NOT EXISTS `vrstausluge` (
  `VRSTAUSLUGE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAZIV` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VIDLJIVO` bit(1) DEFAULT NULL,
  PRIMARY KEY (`VRSTAUSLUGE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=9 ;

INSERT INTO `vrstausluge` (`VRSTAUSLUGE_ID`, `NAZIV`, `VIDLJIVO`) VALUES
(1, 'Instalacija OS-a', b'1'),
(2, 'Zamjena grafičke kartice', b'1'),
(3, 'Zamjena hard diska', b'1'),
(4, 'Instalacija antivirusa', b'1'),
(5, 'Konfiguracija modema', b'1'),
(6, 'Konfigurisanje LAN-a', b'1'),
(7, 'Popravka printera', b'1'),
(8, 'Čišćenje cooler-a', b'1');

ALTER TABLE `korisnik`
  ADD CONSTRAINT `FK_bolggaaus8of25ilqwyx6ctk5` FOREIGN KEY (`TIPKORISNIKA_ID`) REFERENCES `tipkorisnika` (`TIPKORISNIKA_ID`);

ALTER TABLE `obavljeniposao`
  ADD CONSTRAINT `FK_23n0532j0vfi8hichpybgugid` FOREIGN KEY (`RASPOREDJENIZADATAK_ID`) REFERENCES `rasporedjenizadatak` (`RASPOREDJENIZADATAK_ID`),
  ADD CONSTRAINT `FK_rqj2qh1veg6pvxla9fexnp2kr` FOREIGN KEY (`VRSTAUSLUGE_ID`) REFERENCES `vrstausluge` (`VRSTAUSLUGE_ID`);

ALTER TABLE `radnizadatak`
  ADD CONSTRAINT `FK_ayvlsrkc6m5vv7udcxk5rhghi` FOREIGN KEY (`KLIJENT_ID`) REFERENCES `klijent` (`KLIJENT_ID`),
  ADD CONSTRAINT `FK_mweelv44lv4n1yug7hevpxbi0` FOREIGN KEY (`KORISNIK_ID`) REFERENCES `korisnik` (`KORISNIK_ID`);

ALTER TABLE `rasporedjenizadatak`
  ADD CONSTRAINT `FK_32527bsqg0565avppt85kb6pt` FOREIGN KEY (`KORISNIK_ID`) REFERENCES `korisnik` (`KORISNIK_ID`),
  ADD CONSTRAINT `FK_4th26di53x8n0hito9634g2ic` FOREIGN KEY (`RADNIZADATAK_ID`) REFERENCES `radnizadatak` (`RADNIZADATAK_ID`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
